export const AppRoutes = {
  LOGIN: "/login",
  SIGNUP: "/signup",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  ONBOARDING_WELCOME: "/onboarding/welcome",
  ONBOARDING_INTRO: "/onboarding/intro",
  HOUSEHOLD: "/onboarding/household",
  CHILDREN: "/onboarding/children",
  PROFILE: "/onboarding/profile",
  ONBOARDING_CHECKIN: "/onboarding/check-in",
  ONBOARDING_PRIORITY: "/onboarding/priority",
  ONBOARDING_GOALS: "/onboarding/goals",
  DISCOVERY: "/discovery",
  HOME: "/home",
  TASKS: "/tasks",
  GOALS: "/goals",
  USER_PROFILE: "/profile",
  PLANNING: "/planning",
  DAILY_ROUTINE: "/daily-routine",
  CALENDAR: "/calendar",
  FAMILY_CONTEXT: "/family-context",
  HOUSEHOLD_OVERVIEW: "/household-overview",
  SPIRITUAL: "/spiritual",
  LEISURE: "/leisure",
  STATISTICS: "/statistics",
  MY_AI: "/my-ai",
  ASSISTANT: "/assistant",
  AI_PROFILE: "/ai-profile",
  PLANNING_ENGINE: "/planning-engine",
  SETTINGS: "/settings",
  NOTIFICATION_SETTINGS: "/settings/notifications",
  CALENDARS_SETTINGS: "/settings/calendars",
  SEMANTIC_PLANNING: "/organization/ai-understanding",
  ADAPTIVE_INTELLIGENCE: "/organization/adaptive-learning",
  PROACTIVE_INTELLIGENCE: "/organization/proactive-ai",
  DAILY_CHECK_IN: "/daily-check-in",
  DAILY_STATE_HISTORY: "/daily-state/history",
  PERSONAL_COACH: "/organization/personal-coach",
  LIFE_KNOWLEDGE: "/organization/life-knowledge",
  TRUST_CENTER: "/settings/trust",
  HOW_AURA_WORKS: "/settings/trust/how-aura-works",
  ADMIN_INSIGHTS: "/admin/insights",
  ABOUT: "/about",
  WHATS_NEW: "/settings/whats-new",
  LAUNCH_CHECKLIST: "/settings/launch-checklist",
} as const;

export type AppRoute = (typeof AppRoutes)[keyof typeof AppRoutes];

export const ONBOARDING_ROUTES: AppRoute[] = [
  AppRoutes.ONBOARDING_WELCOME,
  AppRoutes.ONBOARDING_INTRO,
  AppRoutes.HOUSEHOLD,
  AppRoutes.CHILDREN,
  AppRoutes.PROFILE,
  AppRoutes.ONBOARDING_CHECKIN,
  AppRoutes.ONBOARDING_PRIORITY,
  AppRoutes.ONBOARDING_GOALS,
  AppRoutes.DISCOVERY,
];

/** Routes applicatives — shell global + barre conversation. */
export const APPLICATION_ROUTES: AppRoute[] = [
  AppRoutes.HOME,
  AppRoutes.TASKS,
  AppRoutes.GOALS,
  AppRoutes.USER_PROFILE,
  AppRoutes.PLANNING,
  AppRoutes.DAILY_ROUTINE,
  AppRoutes.CALENDAR,
  AppRoutes.FAMILY_CONTEXT,
  AppRoutes.HOUSEHOLD_OVERVIEW,
  AppRoutes.SPIRITUAL,
  AppRoutes.LEISURE,
  AppRoutes.STATISTICS,
  AppRoutes.MY_AI,
  AppRoutes.ASSISTANT,
  AppRoutes.AI_PROFILE,
  AppRoutes.PLANNING_ENGINE,
  AppRoutes.SETTINGS,
  AppRoutes.TRUST_CENTER,
  AppRoutes.HOW_AURA_WORKS,
  AppRoutes.NOTIFICATION_SETTINGS,
  AppRoutes.CALENDARS_SETTINGS,
  AppRoutes.SEMANTIC_PLANNING,
  AppRoutes.ADAPTIVE_INTELLIGENCE,
  AppRoutes.PROACTIVE_INTELLIGENCE,
  AppRoutes.DAILY_STATE_HISTORY,
  AppRoutes.PERSONAL_COACH,
  AppRoutes.LIFE_KNOWLEDGE,
  AppRoutes.ABOUT,
  AppRoutes.WHATS_NEW,
  AppRoutes.LAUNCH_CHECKLIST,
];

export const APPLICATION_ROUTE_TITLES: Partial<Record<AppRoute, string>> = {
  [AppRoutes.HOME]: "Accueil",
  [AppRoutes.PLANNING]: "Planning",
  [AppRoutes.CALENDAR]: "Calendrier",
  [AppRoutes.TASKS]: "Tâches",
  [AppRoutes.GOALS]: "Objectifs",
  [AppRoutes.DAILY_ROUTINE]: "Mon quotidien",
  [AppRoutes.FAMILY_CONTEXT]: "Contexte familial",
  [AppRoutes.HOUSEHOLD_OVERVIEW]: "Foyer",
  [AppRoutes.USER_PROFILE]: "Mon profil",
  [AppRoutes.SPIRITUAL]: "Espace spirituel",
  [AppRoutes.LEISURE]: "Loisirs",
  [AppRoutes.STATISTICS]: "Statistiques",
  [AppRoutes.MY_AI]: "Mon IA",
  [AppRoutes.ASSISTANT]: "Assistant IA",
  [AppRoutes.AI_PROFILE]: "Mon Profil IA",
  [AppRoutes.PLANNING_ENGINE]: "Planning Engine",
  [AppRoutes.SETTINGS]: "Paramètres",
  [AppRoutes.TRUST_CENTER]: "Confiance & Confidentialité",
  [AppRoutes.HOW_AURA_WORKS]: "Comment Aura fonctionne",
  [AppRoutes.ADMIN_INSIGHTS]: "Aura Insights",
  [AppRoutes.NOTIFICATION_SETTINGS]: "Notifications",
  [AppRoutes.CALENDARS_SETTINGS]: "Calendriers",
  [AppRoutes.SEMANTIC_PLANNING]: "Compréhension IA",
  [AppRoutes.ADAPTIVE_INTELLIGENCE]: "Apprentissage IA",
  [AppRoutes.PROACTIVE_INTELLIGENCE]: "IA proactive",
  [AppRoutes.DAILY_STATE_HISTORY]: "Historique ressenti",
  [AppRoutes.PERSONAL_COACH]: "Coach personnel",
  [AppRoutes.LIFE_KNOWLEDGE]: "Ce que l'IA sait sur moi",
  [AppRoutes.ABOUT]: "À propos",
  [AppRoutes.WHATS_NEW]: "Quoi de neuf ?",
  [AppRoutes.LAUNCH_CHECKLIST]: "Checklist de lancement",
};

export function isOnboardingRoute(pathname: string): boolean {
  return ONBOARDING_ROUTES.some(
    (route) => pathname === route || pathname.startsWith(`${route}/`),
  );
}

export function isApplicationRoute(pathname: string): boolean {
  return APPLICATION_ROUTES.some(
    (route) => pathname === route || pathname.startsWith(`${route}/`),
  );
}

/** Routes accessibles librement une fois l'onboarding terminé. */
export const POST_ONBOARDING_ROUTES: AppRoute[] = [
  ...APPLICATION_ROUTES,
  AppRoutes.DISCOVERY,
  AppRoutes.DAILY_CHECK_IN,
  AppRoutes.ADMIN_INSIGHTS,
];
